# Generated by Django 5.0.1 on 2024-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpo_id', models.CharField(max_length=100)),
                ('cpo_name', models.CharField(max_length=100)),
                ('cpo_email', models.EmailField(max_length=254, unique=True)),
                ('cpo_password', models.CharField(max_length=50)),
            ],
        ),
    ]
