# Generated by Django 5.0.1 on 2024-03-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_cpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cpo',
        ),
    ]
