# Generated by Django 5.0.1 on 2024-03-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_type_tbl_watt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_watt',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type'),
            preserve_default=False,
        ),
    ]
