# Generated by Django 5.0.1 on 2024-04-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_watt_type'),
        ('Guest', '0010_delete_tbl_chargingport'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chargingport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=100)),
                ('port_name', models.CharField(max_length=100)),
                ('port_details', models.CharField(max_length=50)),
                ('port_amount', models.CharField(max_length=50)),
                ('cpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_cpo')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_type')),
                ('watt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_watt')),
            ],
        ),
    ]
