# Generated by Django 5.0.1 on 2024-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chargingport',
            name='type',
        ),
    ]
