# Generated by Django 5.0.1 on 2024-04-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPO', '0003_remove_tbl_chargingport_port_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chargingport',
            name='district',
        ),
    ]
