# Generated by Django 5.0.1 on 2024-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpo_id', models.CharField(max_length=100)),
                ('cpo_name', models.CharField(max_length=100)),
                ('cpo_email', models.EmailField(max_length=254, unique=True)),
                ('cpo_password', models.CharField(max_length=50)),
                ('cpo_stationname', models.CharField(max_length=50)),
                ('cpo_proof', models.FileField(upload_to='Assets/CpoProof/')),
            ],
        ),
    ]
