# Generated by Django 5.0.1 on 2024-03-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_tbl_cpo'),
        ('Guest', '0003_delete_tbl_cpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpo_id', models.CharField(max_length=100)),
                ('cpo_name', models.CharField(max_length=100)),
                ('cpo_contact', models.CharField(max_length=50)),
                ('cpo_email', models.EmailField(max_length=254, unique=True)),
                ('cpo_password', models.CharField(max_length=50)),
                ('cpo_stationname', models.CharField(max_length=50)),
                ('cpo_proof', models.FileField(upload_to='Assets/CpoProof/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
