# Generated by Django 5.0.1 on 2024-03-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_cpo_cpo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cpo',
            old_name='cpo_stationname',
            new_name='station_name',
        ),
        migrations.RenameField(
            model_name='tbl_cpo',
            old_name='cpo_proof',
            new_name='station_proof',
        ),
    ]
