# Generated by Django 5.0.1 on 2024-03-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_rename_cpo_stationname_tbl_cpo_station_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cpo',
        ),
    ]
