# Generated by Django 5.0.1 on 2024-04-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_chargingport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chargingport',
        ),
    ]
