# Generated by Django 4.2.7 on 2024-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
